openapi: 3.0.3
info:
  title: MobiliTeam backend interface
  description: |-
    The title says it all
  version: 1.0.0
components:
  responses:
    InternalServerError:
      description: |-
        The server encountered an internal error.
  schemas:
    mydatetime:
      title: Ubiquitous date time
      description: |-
        Since even the ISO8601 format may be misleading 
        with regards on how the date time is represented,
        and since the user is not giving the server any
        date time, we hereby declare that the server will only
        serve datetimes in the 'YYYY-MM-DD hh:mm:ss' format on zulu time (+00:00),
        the client will see (hopefully) their converted time of course.
      type: string
      format: date-time
      minLength: 19
      maxLength: 19

    lineinfo:
      title: Line info
      description: |-
        This object contains all of a line's info at a certain point in time
      type: object
      properties:
        stops:
          description: List of stops followed by the line
          type: array
          items:
            type: string
          minItems: 2
          maxItems: 64
        buses:
          description: List of buses servicing the line
          type: array
          items:
            type: string
          minItems: 1
          maxItems: 64
      
    businfo:
      title: Bus info
      description: |-
        This object contains all of a bus's info at a certain point in time
      type: object
      properties:
        timeleft:
          description: Expected time before arriving to the next stop
          type: integer
        laststop:
          description: Last stop done by the bus
          type: string
        overcrowded:
          description: Whether the bus is currently overcrowded
          type: boolean
paths:
  /lines/{line}:
    parameters:
      - in: path
        name: line
        schema:
          type: string
        required: true
    get:
      summary: Get this line's info
      description: Returns all of a line's info, including stops and buses currently travelling on the line
      operationId: getLineInfo
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lineinfo'
        '404':
          description: Line not found
        '500':
          $ref: '#/components/responses/InternalServerError'
  /buses/{bus}:
    parameters:
      - in: path
        name: bus
        schema:
          type: string
        required: true
    get:
      summary: Get this bus's info
      description: Returns as specific bus's info
      operationId: getBusInfo
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/businfo'
        '404':
          description: Bus not found
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      summary: Board/overcrowd bus
      description: Sets a specific bus's info
      operationId: setBusInfo
      requestBody:
        content:
            application/json:
              schema:
                type: object
                properties:
                  overcrowded:
                    description: Whether the bus is currently overcrowded
                    type: boolean
                  boardedat:
                    description: Where the bus was boarded
                    type: string
        required: true
      responses:
        '204':
          description: Successful operation
        '400':
          description: Request badly formed
        '404':
          description: Bus not found
        '500':
          $ref: '#/components/responses/InternalServerError'